### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by mrapolo2020** [mrbizarro/phosphene#34]
## Environment
- Phosphene version: 3.2.5 (fbc6335)
- Branch: main
- macOS: 26.5.2
- Mac: Mac16,7 · 48 GB RAM

## Logs / repro
```
[13:41:35] caffeinate active — Mac won't idle-sleep while queue is running
[13:41:35] Balanced on Comfortable hardware → Q8 Fast routing (stage1=10, teacache=1.0; ~6 min, Q8 dev source).
[13:41:35] Run HIGH via helper: id=j-19f41519c35-001 mode=t2v 1024x576 121f · Q8 two-stage HQ + TeaCache · memory=auto VAE=full
[13:41:35] Spawning warm helper (low_memory=true, idle_timeout=1800s)
[13:41:35] runtime | mlx=0.31.1 mlx-metal=0.31.1 | chip=Apple M4 Pro | macOS=26.5.2 (arm64)
[13:41:35] helper ready · model=/Volumes/T7/phosphene/phosphene-repo/mlx_models/ltx-2.3-mlx-q4 · low_memory=True · ltx-2-mlx=0.14.8 · mlx=0.31.1 · Apple M4 Pro
[13:41:35] accel:mode off patched=samplers,distilled,ti2vid_two_stages,ti2vid_two_stages_hq,keyframe_interpolation,a2vid_two_stage,lipdub,ic_lora
[13:41:35] Loading HQ pipeline (Q8 dev model — /Volumes/T7/phosphene/phosphene-repo/mlx_models/ltx-2.3-mlx-q8)...
[13:41:35] pipeline.generate_and_save doesn't accept ['audio_skip_step', 'bongmath_max_iter', 'stage2_image_conditioning', 'video_skip_step']; dropping.
[13:41:35] [Loading text encoder (Gemma)] ...
[13:41:38] Stop requested — killing helper + ffmpeg post-process + training subprocess to abort current job.
[13:41:38] helper SIGTERM sent (pgid 56753)
[13:41:38] Job cancelled.
[13:41:44] stats: no GitHub token resolvable (tried PHOSPHENE_REPO_STATS_TOKEN, GH_STATS_TOKEN, GH_TOKEN, GITHUB_TOKEN, `gh auth token`). Dashboard will be empty until you set one. See docs/stats-README.md.
[13:42:06] [enhance] t2v: a man at a cafe…
[13:42:06] Spawning warm helper (low_memory=true, idle_timeout=1800s)
[13:42:06] runtime | mlx=0.31.1 mlx-metal=0.31.1 | chip=Apple M4 Pro | macOS=26.5.2 (arm64)
[13:42:06] helper ready · model=/Volumes/T7/phosphene/phosphene-repo/mlx_models/ltx-2.3-mlx-q4 · low_memory=True · ltx-2-mlx=0.14.8 · mlx=0.31.1 · Apple M4 Pro
[13:42:06] Loading Gemma language model for prompt enhancement (~10-15s)…
[13:42:09] Gemma loaded — subsequent enhances will be fast.
[13:42:21] [enhance] → Style: cinematic-realistic. A man in his late 20s with short dark hair and a neatly trimmed beard sits at a wrought iron… (14.71s)
[13:44:54] [deep-verify] DONE — all 16 weight file(s) match upstream.
[13:46:14] Stop requested — killing helper + ffmpeg post-process + training subprocess to abort current job.
[13:46:14] helper SIGTERM sent (pgid 56850)
[13:46:14] Stop requested — killing helper + ffmpeg post-process + training subprocess to abort current job.
[13:46:14] Stop requested — killing helper + ffmpeg post-process + training subprocess to abort current job.
```

**Comment by mrbizarro** [comment]
The report body came through empty, so I can't tell what actually went wrong — the log you pasted just shows a job you **cancelled** (a Stop was pressed a few seconds in), plus a harmless "no GitHub token" note for the stats dashboard.

If your generations are failing with `'str' object has no attribute '__module__'`, that's the `transformers 5.13.0` regression (tracked in #40) — fix it now from your Phosphene folder in the Pinokio Terminal:
```
cd ltx-2-mlx
uv pip install --python env/bin/python 'transformers>=5.0.0,<5.13.0'
```
If it's something else, could you edit the issue with what you were doing, what happened, and the actual error line? Happy to dig in once I can see it. Leaving open for your reply.

**Comment by mrbizarro** [comment]
@mrapolo2020 — circling back. The report body came through empty, so I never saw what actually failed. If it was the `'str' object has no attribute '__module__'` crash, that's fixed in v3.2.6 — just hit Update in Pinokio. If it's something else and still happening, drop the actual error line + what you were doing and I'll dig in; otherwise I'll close this as resolved in a few days. No rush.

**Comment by mrbizarro** [comment]
Closing this one out as promised — the report body came through blank, and without what you were doing or a real error line there's nothing here I can reproduce. The log you attached only shows a job that was cancelled a few seconds in.

For the record, in case one of these was it:

- `'str' object has no attribute '__module__'` on every generation — fixed in v3.2.6.
- The `stats: no GitHub token` line in your log is cosmetic (maintainer stats panel only, never touches generation) — it's been quieted since.

Current version is v3.4.1 via Pinokio → Update, which has both.

If you're still hitting something, comment here with the actual error line and what you were doing and I'll reopen right away. Sorry it stalled, and thanks for taking the time to file it.
