### ISSUE TITLE
T2V render fails instantly on 16GB Compact tier — "Model not loaded. Call load() first."

### ISSUE THREAD

**Issue by xandreau** [mrbizarro/phosphene#33]
Environment: Mac Mini, 16GB RAM (Compact tier), Phosphene 3.0 via Pinokio, Pinokio home on external Thunderbolt SSD. Models 2/2 required installed, startup log shows "model integrity: OK (8 weight files verified)", helper warm.
Steps: Video → Text mode → short prompt → Quality: Quick (640×480) → Generate. No Enhance/Avoid/No music/No voice, no LoRAs.
Result: Fails within ~1 second. Log:

[00:53:27] Run via helper: id=j-19f3369ed40-002 mode=t2v quality=quick accel=off 640x480 121f · memory=safe VAE=stream
[00:53:27] step:get_pipe kind=t2v
[00:53:27] step:get_pipe done
[00:53:27] step:generate mode=t2v 640x480 121f @24.0fps steps=8 accel=off
[00:53:28] [Loading text encoder (Gemma)] ... done in 0.0s
[00:53:28] [Encoding prompt] ... done in 0.0s
[00:53:28] ERROR: Model not loaded. Call load() first.

An earlier attempt showed: 'str' object has no attribute '__module__'. Note the 0.0s "loads" — the encoder steps appear to no-op.
Already tried: full uninstall/reinstall; deleted partial Q8 download; recreated state folder; minimal settings. Same result every time.

26.5.2
Apple M4

**Comment by xandreau** [comment]
Reproduced on two machines:

MacBook Pro, Apple M4 Pro, macOS 26.5.2 — Phosphene v3.2.4 (recommended), fresh install
Mac Mini, 16GB (Compact tier) — v3.2.5 and v3.0.13, multiple fresh installs

Steps: T2V → short prompt → Quick 640×480 → Generate. No Enhance/LoRAs/toggles.
Log (MacBook Pro, v3.2.4):

[02:22:19] runtime | mlx=0.31.1 mlx-metal=0.31.1 | chip=Apple M4 Pro | macOS=26.5.2 (arm64)
[02:22:19] helper ready · model=.../mlx_models/ltx-2.3-mlx-q4 · low_memory=True · ltx-2-mlx=0.14.8 · mlx=0.31.1
[02:22:19] step:generate mode=t2v 640x480 121f @24.0fps steps=8 accel=off
[02:22:19] [Loading text encoder (Gemma)] ...
[02:22:33] [Loading text encoder (Gemma)] done in 13.2s
[02:22:33] ERROR: 'str' object has no attribute '__module__'

On the Mini, subsequent attempts show encoder steps completing in 0.0s followed by ERROR: Model not loaded. Call load() first. — apparently a stuck state after the first failure.
Note: Models were freshly downloaded July 5–6, 2026 (Q4 + gemma-3-12b-it-4bit). Ruled out: reinstalls, state reset, partial-download cleanup, version rollback. Possibly an upstream change in the Gemma HF repo breaking new downloads?

**Comment by xandreau** [comment]
Root cause found (with help from an evening of debugging on two machines and a lot of help from ClaudeAI)
The installer doesn't pin the transformers version. New installs currently pull in transformers 5.13.0, which is incompatible with the pinned mlx-lm 0.31.1: at import, mlx_lm/tokenizer_utils.py (line 427) calls

AutoTokenizer.register("NewlineTokenizer", fast_tokenizer_class=NewlineTokenizer)

passing a string as the config class. transformers 5.13's auto_factory.py register() (line 680) then does:

if key.__module__.startswith("transformers."):

which raises AttributeError: 'str' object has no attribute '__module__'.
In the panel this surfaces as an instant job failure — first as 'str' object has no attribute '__module__', then on subsequent attempts as Model not loaded. Call load() first. (with the Gemma load steps reporting "done in 0.0s"). This explains why it reproduces on fresh installs (both my Mac Mini 16GB and MacBook Pro M4 Pro, versions 3.0.13 / 3.2.4 / 3.2.5) while presumably working on machines with an older transformers already in the environment.
Workaround confirmed on both machines:

./ltx-2-mlx/env/bin/pip install "transformers<5"

(installs 4.57.6; pip warns that mlx-lm/mlx-vlm/mflux want transformers ≥5, but T2V rendering works — verified via both the ltx-2-mlx CLI and the Phosphene panel).
Suggested fix: pin transformers (and possibly huggingface-hub) in the installer to versions known to work with mlx-lm 0.31.1 — or, if the newer image features need transformers 5.x, a middle version <5.13 may satisfy both (untested).

**Comment by mrbizarro** [comment]
Same root cause as #40: `transformers 5.13.0` broke `mlx-lm`'s tokenizer, so the Gemma encoder no-ops (note your "done in 0.0s") → "Model not loaded" / `'str' object has no attribute '__module__'`. Not a 16 GB-tier problem after all.

Fix now, from your Phosphene folder in the Pinokio Terminal:
```
cd ltx-2-mlx
uv pip install --python env/bin/python 'transformers>=5.0.0,<5.13.0'
```
The permanent pin is in install.js (lands via Update in the next patch). Closing as a duplicate of #40 — follow that one for the release. Thanks for the detailed logs, they made this fast to pin down.
